---
- hosts: all
  become: yes
  tasks:
      - name: install webserver in ubuntu
        apt:
            name: apache2
            state: present
        when: ansible_os_family == "Debian"

      - name: install webserver in rhel
        yum:
            name: httpd
            state: presen
        when: ansible_os_family == "RedHat"

      - name: restart service in ubuntu
        service: 
          name: apache2
          state: restarted 

      - name: Restart Apache
        service:
          name: "{{ services }}"
          state: restarted
          enabled: yes
        become: true
        vars:
          services:
          - httpd